version: "3.8"
services:
  betest:
    container_name: iqbal_betest
    build: .
    networks:
      - node-network
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      HOSTMONGO: mongo1
      PORTMONGO: 27017
      HOSTREDIS: redis1
      PORTREDIS: 6379
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongo1
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - node-network
  redis:
    container_name: redis1
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - node-network
networks:
  node-network:
volumes:
  mongodb-data:
